### ISSUE TITLE
Práctica Graficación 

### ISSUE THREAD

**Issue by LeinnaMora** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-equipo-ximena-karen-1as#1]
[practicaSphereo_MatematicasDiscretas.pdf](https://github.com/user-attachments/files/17155539/practicaSphereo_MatematicasDiscretas.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by Eddi3mendoz** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20
Califico Edwin Eduardo Mendoza Cruz

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
